version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: pei/bra_angular
    container_name: BinaryRiskAnalysis
    ports:
      - 4201:4200
    restart: always
  dev:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
     - .:/code